name: TerraCraft
load: POSTWORLD
version: ${project.version}
main: de.docbrumm.terracraft.TerraCraft
api-version: 1.16
authors: 
  - DocBrumm
  - MoMMde
description: Play Terraria, a 2D Game, in Minecraft.
website: docbrumm.stckoverflw.de



commands:
  language:
    description: Change your Language ingame
    permission: terracraft.language.inventory
