name: TerraCraft
load: STARTUP
version: ${project.version}
main: de.docbrumm.terracraft.TerraCraft
api-version: 1.16
authors: 
  - DocBrumm
  - MoMMde
description: Play Terraria, a 2D Game, in Minecraft.
website: docbrumm.stckoverflw.de
softdepend:
  - ProtocolLib

commands:
  language:
    description: Change your Language ingame
    permission: terracraft.language.inventory
  createnpc:
    description: Create a NPC